### ISSUE TITLE
Multiprocessing and Python 3.8

### ISSUE THREAD

**Issue by piyushrpt** [isce-framework/isce2#146]
Python 3.8 multiprocessing uses “spawning” instead of “forking” due to security reasons. The different ampcor threads dont get the complete context to generate image accessors correctly when using denseampcor / denseoffsets. This can be overcome by adding 

```
mp.set_start_method("fork")
```
before using any multiprocessing features. This should only be done for osx + python3.8

**Comment by hfattahi** [comment]
Thank you @piyushrpt . @vbrancat  and I have not been able to reproduce issues with denseoffsets as reported by @parosen because we have python 3.7. 

Do you think if the only place one needs to add your fix, would be here:
https://github.com/isce-framework/isce2/blob/master/components/mroipac/ampcor/DenseAmpcor.py#L378
Do you think if there is any other place which needs change?

**Comment by piyushrpt** [comment]
I think that should be the only place needed for the workflows. The only other place that I can think of where multiprocessing is used is in topsStack contributed by @mirzaees
