### ISSUE TITLE
TypeError: runGeocode() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by HBaldwin3** [isce-framework/isce2#182]
Not sure how to resolve this error (posted to user forum as well: http://earthdef.caltech.edu/boards/4/topics/3295?r=3553#message-3553)

https://github.com/isce-framework/isce2/blob/b13d06aa3b981119d32c9da7dd1bb244622bed1e/components/isceobj/RtcProc/Factories.py#L40

![image](https://user-images.githubusercontent.com/49163135/91048065-b7f5dd80-e5e0-11ea-9262-53574ff2339a.png)

**Comment by bjmarfito** [comment]
This could be possibly a problem on the rtcApp.py where on line nos. 427 to 428 shows a function needing three arguments instead of just one argument. 
[https://github.com/isce-framework/isce2/blob/f65a51c80c2605001ebe6f97dd98f7b45bc1d919/applications/rtcApp.py#L427](url)
[https://github.com/isce-framework/isce2/blob/f65a51c80c2605001ebe6f97dd98f7b45bc1d919/applications/rtcApp.py#L428](url)

This could possibly be solved by removing the args=(self.geocode_list, self.geocode_bbox) on rtcApp.py or add those arguments on the runGeocode.py on the RtcProc folder.

**Comment by bjmarfito** [comment]
I checked the runGeocode.py on the RtcProc folder. There is no used if the code will incorporate self.geocode_list, self.geocode_bbox. I suggest removing it on the rtcApp.py.

**Comment by bjmarfito** [comment]
I generated a PR to resolve this issue. [https://github.com/isce-framework/isce2/pull/220](url)
