### ISSUE TITLE
Unwrap and geocode error

### ISSUE THREAD

**Issue by SiriusXCH0103** [isce-framework/isce2#296]
ISCE 2.5
I prepared 2 paris of images to stitch to a larger one, and processed automatically using "topApp.py tops.xml".
However, the unwrapping and geocoding steps made some mistakes. 
I can get normal "filt_topophase.flat.geo" and "filt_topophase.unw" files, but the "filt_topophase.unw.geo" file is wrong.
Here are the images of these files shown by "mdx.py".
![flat](https://user-images.githubusercontent.com/48155788/120056482-128c0080-c06f-11eb-97fd-26987c926aba.jpg)
filt_topophase.flat.geo

![unw](https://user-images.githubusercontent.com/48155788/120056485-1fa8ef80-c06f-11eb-823c-a20305154584.jpg)
filt_topophase.unw

![unw geo](https://user-images.githubusercontent.com/48155788/120056488-2899c100-c06f-11eb-9278-9d28d515e461.jpg)
filt_topophase.unw.geo

As a result, the LOS displacement becomes: 
![qinghai_los](https://user-images.githubusercontent.com/48155788/120056180-29c9ee80-c06d-11eb-9190-499847fa6e29.png)

What's the reason of this result? And how to solve it?
Besides, why the image of "filt_topophase.unw.geo" shown by "mdx.py" is always gray, not color?

**Comment by hfattahi** [comment]
Would you please tell us what is the error exactly that you are concerned about?

**Comment by SiriusXCH0103** [comment]
> Would you please tell us what is the error exactly that you are concerned about?

The value of "filt_topophase.unw.geo". Its upper part has a large value and the lower part is almost all black (pic 3). When converted to LOS displacement, it should be a certain area around the fault that has deformed, not the entire side has moved as the last pic shows. So this result must be wrong. What's the reason of this error？

**Comment by hfattahi** [comment]
This is a difficult case to unwarp properly. The high fringe rate and low correlation along the rupture prevents unwrapping to go across the fault. Maybe with proper masking an advanced user can get the expected unwrapping results. Otherwise unwrapping errors in interferograms like this one can not be avoided.

**Comment by EJFielding** [comment]
For large earthquakes with surface ruptures, it is difficult for the unwrapping to know where to put the discontinuities. Setting the filter strength in `topsApp.xml` to a low value sometimes helps, but this kind of large coseismic deformation usually requires extra steps to get a good result, as @hfattahi mentioned. I am still trying to get a good unwrapping myself.

**Comment by farabi77** [comment]
One of the unwrap results is "connected components", I don't know what can we use it to do, remove areas with low coherence? I often use it by topophase.cor.geo file to filter. I met the same error about maduo earthquake, has anyone used isce2 to get a better result?

**Comment by EJFielding** [comment]
The connected components output layer is calculated in SNAPHU by first applying a threshold to the coherence or correlation (`topsApp.py` passes `phsig.cor` to the SNAPHU module). The low-coherence areas are set to zero on the connected components, so one use of the connected components is to mask out areas of low coherence by removing pixels that are set to zero in `filt_topophase.unw.conncomp` or `filt_topophase.unw.conncomp.geo`. I do this often.![A099-conncomp-overview-LL](https://user-images.githubusercontent.com/7253576/130361333-609d17e6-b34d-461e-b996-280756eba926.jpeg)
The second calculation that SNAPHU does is search through the image of pixels above the threshold to find the areas or components of the image that are connected. It keeps the 20 components with the largest number of pixels with the default settings. You can look at the connected components to see the areas that are likely to be unwrapped to the same ambiguity. If two areas are in different components, this means that there could be an unwrapping error between those areas and some multiple of 2-pi needs to be added or subtracted to correct it. For the Maduo, Qinghai earthquake, the A099 pair `filt_topophase.unw.conncomp.geo` connected components looks like the map above. The big area north of the fault and the big area south of the fault are in different connected components (south is 1 and north is 12), so SNAPHU had to use low coherence areas to estimate the unwrapping between the two and it gets the wrong answer. You can try to correct it by selecting all the pixels in component 12 and adding or subtracting a multiple of 2-pi from the phase to get it closer to the phase of component 1. Note that there are a number of smaller areas that are also in separate components, and the adjustment of these could also be done, but when you are close to the fault rupture (green line), then there could be a real jump in phase between the areas due to large deformation.
