### ISSUE TITLE
How to do the Terrain Correction in ICSE?

### ISSUE THREAD

**Issue by PeymanPython** [isce-framework/isce2#432]
Dear all,
I have used the ISCE to generate the ifgs and got some pleasant results by the following workflow:

"(insar) user@user-B250-HD3:/mnt/mydisk/merged/interferograms/20211109_20211121$ stackSentinel.py -s /mnt/mydisk/SLC/ -d /mnt/mydisk/DEM/demLat_N27_N28_Lon_E055_E057.dem.wgs84 -a /mnt/mydisk/Aux_file/ -o /mnt/mydisk/orbits/ -b '27.2 27.95 55.55 56.7' -m 20211109 -c all -r 5 -z 1 -C geometry -W interferogram" 

Could you please let me know how to do the terrain correction? or get the ".geo" format of ifgs? Any help would be much appreciated.

![ifg](https://user-images.githubusercontent.com/55481769/149986439-650c4382-613b-43ef-b81d-569d0fbafe43.png)

**Comment by hfattahi** [comment]
One more thing that you could check is the height in radar coordinates. Could you take a look at this file and perhaps display it:
```merged/geom_reference/hgt.rdr```

**Comment by PeymanPython** [comment]
**@hfattahi** Many Thanks for your prompt reply.
- Concerning the DEM coverage:
As you can see, the extent of the "bbox" is smaller than what I have considered for DEM. So, DEM covers the bbox completely:
DEM extent: N27_N28_Lon_E055_E057
BBOX extent: '27.2 27.95 55.55 56.7'

- But in the case of the DEM's pixel value:
I've just checked the total of DEM coverage and can show a screen of the DEM and it shows that it has proper values:

![DEM](https://user-images.githubusercontent.com/55481769/150357104-cc17a1d3-a64a-4e96-8765-a8542bf99871.png)

One thing more is that there is an oblique line in the upper part of the ifg! Is there any problem regarding that line? Of course, am not sure but I think it must be due to the DEM coverage. If so, should I consider a DEM extent that covers all 3 IW's of Sentinel-1 acquisition?
![Line](https://user-images.githubusercontent.com/55481769/150362618-b691df99-b17b-4fd6-a1e4-7b52bc38e3a4.png)
![Line2](https://user-images.githubusercontent.com/55481769/150363142-c178ced2-4a7f-44e9-a820-aa2ed7a079f9.png)
![Uploading Line2.png…]()

**Comment by hfattahi** [comment]
@PeymanPython Your DEM does not cover the entire interferogram. Use a larger DEM please.

**Comment by PeymanPython** [comment]
@hfattahi 
Thanks again. I'll try to use a bigger extent of DEM. 
So, do you mean the not corrected terrain is because of the DEM issue? Another matter is that I have the "run_11_unwrap" file in the "run_files" but there is no unwrapped ifg in the merge/interferograms folder! Are the all issues because of DEM?

**Comment by PeymanPython** [comment]
@hfattahi
I used a larger DEM (### stackSentinel.py -s .../SLC/ -d .../DEM/demLat_N26_N28_Lon_E054_E058.dem.wgs84 -a .../Aux_file/ -o .../orbits/ -b '27.2 27.95 55.55 56.7' -m 20211109 -c all -r 5 -z 1 -C geometry -W interferogram) but nothing has changed and I have no Terrain Corrected interferogram. Also, the mentioned oblique line in ifg not removed!

Thanks in advance for your informative help.

**Comment by hfattahi** [comment]
Can you zoom out and display all the interferogram? 
for the subset you showed above, part of the interferogram is flattened (below the oblique line) and part is not. 
It looks like your DEM still does not cover your scene. Most likely you extended your DEM in the wrong direction. Try to extend in the North direction.

**Comment by PeymanPython** [comment]
Fullscreen of ifg:

![Full-ifg](https://user-images.githubusercontent.com/55481769/150480213-f79f34ab-79c1-483c-8ee0-4ff0ccdf6d80.png)

**Comment by PeymanPython** [comment]
@hfattahi 
I've changed the DEM extent once again, and there is no oblique line anymore. But it needs to be "Terrain Corrected" and I do not know how to do it.
Using the following workflow:
"""stackSentinel.py -s ..../SLC/ -d ..../DEM/demLat_N26_N31_Lon_E055_E057.dem.wgs84 -a .../Aux_file/ -o .../orbits/ -b '27.2 27.85 55.7 56.8' -m 20211109 -c all -r 5 -z 1 -C geometry -W interferogram"""

![Full-Screen](https://user-images.githubusercontent.com/55481769/150535922-bf63b8be-c44c-46a1-abde-cc8048ff6c7a.png)
![Full_Screen](https://user-images.githubusercontent.com/55481769/150536772-1d848362-25ec-4bac-a663-1187d71dfc9e.png)

**Comment by hfattahi** [comment]
I assume by Terrain Corrected you mean "flattening", i.e. removing interferometric phase due to baseline separation between the two images, which basically removes topographic phase.

If that's what you mean, this interferogram is already flattened. Just look at your early screenshots before using the correct DEM where you had the clear discontinuity. Look how fringes are different below and above that line. Below the line the topographic phase is removed. Above the line the topographic phase was not removed because the DEM was not covering the area above the line. That is gone now. The interferogram is flattened except for the left side which your DEM still does not cover the scene yet (but probably you are not concerned about it).  

The interferogram can not be completely flat. Because there are tropospheric, ionospheric delay or maybe residual topographic phase due to DEM inaccuracy. 

Do you expect a geophysical event in this interferogram? Is the fringe pattern in the middle an earthquake?

**Comment by PeymanPython** [comment]
Dear @hfattahi, 
You can compare the well-located features in DEM and their corresponding situation in the interferogram. So I should do a correction to set them in their real location that is called "Range Doppler Terrain Correction" in some software like SNAP.

**Comment by hfattahi** [comment]
I see what do you mean. Your interferogram above is in radar coordinates. The fact that your east and west is swapped, is because it is descending. You need to geocode the interferogram to have it on the grid that you want. 
I suggest to read our material in [UNAVCO workshops](https://github.com/isce-framework/isce2-docs/tree/master/Notebooks
) where we have been teaching these basics.
BTW, stack processor is for advanced users. I suggest to use topsApp instead, and get back to stack processor when you feel comfortable with the concept, tools and changing some python scripts when needed. 

Since there is no bug/issue with the software please go ahead and close this issue.

**Comment by PeymanPython** [comment]
Thanks a lot for all your efforts.

**Comment by PeymanPython** [comment]
I beg your pardon for reopening the issue. I have just one more request to guide:
Could you please let me know if I must change codes in any stack processor application (like rtcApp.py) to solve the problem?
Or if it's possible let me contact you privately.

**Comment by zhuhaxixiong** [comment]
> 

doee the topsApp or stripmapApp remve the flat eath phase and topographic phase in the inteferogram?
