### ISSUE TITLE
 Phase discontinuities in the burst overlap areas after 'run_09_merge_burst_igram'

### ISSUE THREAD

**Issue by vic-chou** [isce-framework/isce2#532]
Dear all,
    When I use stackSentinel.py to generate intergerograms, I find the results (filt_fine.unw) look strange (see below figure). There are obvious phase discontinuities in the burst overlap areas. I think there may be some problems in the step of 'run_ 09_merge_burst_igram'. The dates of the intergerograms is  2014/10/20-2014/11/13. I hope someone can help me. Thank you!
<img width="571" alt="image" src="https://user-images.githubusercontent.com/23021653/179380163-964ffe43-12f7-4f29-808f-1f00d0f2a70e.png">

**Comment by yuankailiu** [comment]
Hi @vic-chou, is this an ascending track dataset (acquired in dusk time)? If yes, what you see is probably the phase discontinuities in the burst overlap areas caused by the ionosphere. Please see [the following paper in Section II.C](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8706258). Also, figure 5, 7 therein. So this would be a real observation due to the imaging geometry of the TOPS mode coupled with the ionospheric phase.

I can see from your interferogram that there is a clear dominant spatial ramp and those burst jumps. They are probably both effects of the ionosphere.

`topsApp.py` can estimate and remove the smooth ionosphere phase (the ramp) and these ionospheric burst jumps on a pair-by-pair fashion.

`stackSentinel.py` has a similar workflow, but it can only [estimate the smooth ionosphere phase](https://github.com/isce-framework/isce2/blob/main/contrib/stack/topsStack/README.md#ionospheric-phase-estimation) (it does not have the functionality to account for those burst jumps yet.). Then you will have to subtract the ionosphere phase from your interferogram in postprocessing yourself. Thus, if you use `stackSentinel.py` to estimate the ionosphere, you could probably remove the ramp but not the burst jumps.

Are you doing a large spatial extent and long time-series analysis at the end? Are you looking for a large signal (coseismic)? Whether these burst jumps matter will depend on what you need, I think.

**Comment by vic-chou** [comment]
> Hi @vic-chou, is this an ascending track dataset (acquired in dusk time)? If yes, what you see is probably the phase discontinuities in the burst overlap areas caused by the ionosphere. Please see [the following paper in Section II.C](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8706258). Also, figure 5, 7 therein. So this would be a real observation due to the imaging geometry of the TOPS mode coupled with the ionospheric phase.
> 
> I can see from your interferogram that there is a clear dominant spatial ramp and those burst jumps. They are probably both effects of the ionosphere.
> 
> `topsApp.py` can estimate and remove the smooth ionosphere phase (the ramp) and these ionospheric burst jumps on a pair-by-pair fashion.
> 
> `stackSentinel.py` has a similar workflow, but it can only [estimate the smooth ionosphere phase](https://github.com/isce-framework/isce2/blob/main/contrib/stack/topsStack/README.md#ionospheric-phase-estimation) (it does not have the functionality to account for those burst jumps yet.). Then you will have to subtract the ionosphere phase from your interferogram in postprocessing yourself. Thus, if you use `stackSentinel.py` to estimate the ionosphere, you could probably remove the ramp but not the burst jumps.
> 
> Are you doing a large spatial extent and long time-series analysis at the end? Are you looking for a large signal (coseismic)? Whether these burst jumps matter will depend on what you need, I think.

Hi @yuankailiu, thanks for your detailed reply. And I am sorry for the later reply. As you said, the interferogram is an ascending track data which is acquired in dusk time (19:58:03, local time). I also read the paper (Liang et al., 2019) you mentioned. My result looks similar with the figure 5 and 7. Your reply helped me find the direction to solve the problem. I am trying to solve the phase discontinuities based on your suggestions. If I can obtain a good result, I'll shared with you. 
I want to do a large spatial extent and long time-series analysis at the end. I am looking for interseismic signal. Maybe I can test  how this ionospheric phase will affect my final results in this area. Thank you again! Your enthusiastic response has given me more motivation
