### ISSUE TITLE
Issue with Flat earth correction in TopsApp

### ISSUE THREAD

**Issue by ayush12gupta** [isce-framework/isce2#636]
I tried generating interferrogram using topsApp.py, but its giving a strange fringes as shown below:
![Screenshot from 2022-12-10 16-47-04](https://user-images.githubusercontent.com/56562280/206852331-197c9310-5a62-4cdb-bb3e-e81cfd16d79c.png)
And when I turned off the flattening it was giving the correct fringes which were matching or were similar to that obtained from SNAP. I computed the residual of **topophase.flat** obtained with and without flatenning, and obtained this : 
![image](https://user-images.githubusercontent.com/56562280/206852450-5c8269ad-31cc-41a3-bc72-bf8220a7f8c1.png)

And as far as I know the flat earth phase must have using form fringes from left to right, which is not at all the case here.

Can you please suggest what is the issue here or am I doing something wrong with parameter input

**Comment by ayush12gupta** [comment]
I even have doubts regarding how the flat earth correction is being implemented since, as in runBurstIfg.py 
![Screenshot from 2022-12-09 11-29-12](https://user-images.githubusercontent.com/56562280/206852626-79b97955-5168-4703-a4c8-45bcc482a4e4.png)
The additional terms of flat earth correction i.e. perpendicular baseline and tan( incidennce angle ) are not being used in the variable **fact** as shown in the snippet above. And the formula for flat earth correction is the second term of the equation given below:
![Screenshot from 2022-12-09 11-30-16](https://user-images.githubusercontent.com/56562280/206852742-00a65ef7-cc4e-43e8-bffd-3cb10ba146eb.png)

**Comment by piyushrpt** [comment]
Break down of InSAR phase components into flat earth and then topography is a conceptual idea, and these equations related to perpendicular baseline are largely something used to explain the concepts. This idea is from the era when InSAR was largely used to generate DEMs. Removing the flat phase reduced fringe rate to assist unwrapping. For differential InSAR for deformation applications, you can take out flat phase and topography component in one shot - because the radar does not image flat earth and topography independently. What the radar observes is the combined effect of everything. Consequently, the range.off files represent the combined effect of all topography.

**Comment by ayush12gupta** [comment]
Ok thanks, so is there some way of generating InSAR image which is having its topographic phase i.e. we just remove flat earth phase.

**Comment by piyushrpt** [comment]
You can provide an all zero DEM and just do the same processing. In that case, you will be left with topographic fringes.

**Comment by ayush12gupta** [comment]
Ok thanks
