### ISSUE TITLE
run_16_unwrap  -> "killed"

### ISSUE THREAD

**Issue by alevasca** [isce-framework/isce2#644]
Hello everyone,

I'm having a problem with run 16 (unwrap) of stackSentinel (with a multilooking of 5r x 1a). Just after starting it, the process is killed as you can see in the attached screenshot. I'm assuming that it has to do with the RAM. Running this step, the RAM (16 GB) reaches a load of ca. 97% and then the process gets killed. Has anybody ever dealt with that before? 

![image](https://user-images.githubusercontent.com/82417925/210024525-c7eda173-91ff-4d0d-a1a6-49ba01163fbf.png)

Cheers

**Comment by EJFielding** [comment]
When you get the "Killed" message from Linux, it is almost always because the computer ran out of RAM. You would need a huge amount of RAM to unwrap a whole Sentinel-1 scene with a multilooking of only 5 range and 1 azimuth look, probably more than 64 GB. You either have to find a computer with more memory or reduce the size of the subset you are unwrapping if you don't want to increase the looks.

**Comment by alevasca** [comment]
Hi Eric, thanks for replying. Indeed! The "killed" message was related to the RAM. With more RAM the processing finished successfully!
Cheers,
Alejandra

**Comment by xilaile666** [comment]
How do you clear the RAM?

**Comment by EJFielding** [comment]
@xilaile666 To reduce the RAM usage by the unwrapping step, the best way is to take more looks and reduce the interferogram size.
