### ISSUE TITLE
cmake install issue

### ISSUE THREAD

**Issue by cyloveyou** [isce-framework/isce2#828]

**Comment by cyloveyou** [comment]
Hello all! I'm trying to install isce2 following the cmake method and come across an error at 95%. Does anyone knows what can be wrong? I have ubuntu 22.04 and anaconda. Thanks!

**Comment by rtburns-jpl** [comment]
CMake is linking against /usr/local/lib/libfftw3f.a from your distro, which is a static lib and can't be linked into shared objects. You should make sure that cmake finds shared libraries (ending in .so) for fftw. If you're using conda, you should probably install fftw using conda rather than using the one from your distro.
