### ISSUE TITLE
alosStack estimated interferogram coherence larger than 1

### ISSUE THREAD

**Issue by ehavazli** [isce-framework/isce2#847]
I am processing ALOS-2 ScanSAR data and I ran into a case where the estimated interferogram coherence exceeds 1:
```
Band 1 Block=5129x1 Type=Float32, ColorInterp=Undefined
  Minimum=0.000, Maximum=897447.438, Mean=8561.947, StdDev=5409.711
  Metadata:
    STATISTICS_MAXIMUM=897447.4375
    STATISTICS_MEAN=8561.9472832599
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=5409.7114304967
    STATISTICS_VALID_PERCENT=100
Band 2 Block=5129x1 Type=Float32, ColorInterp=Undefined
  Minimum=0.000, Maximum=1.201, Mean=0.487, StdDev=0.237
  Metadata:
    STATISTICS_MAXIMUM=1.2005478143692
    STATISTICS_MEAN=0.48689489981335
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=0.23687659024294
    STATISTICS_VALID_PERCENT=100
```

The `.cor.xml` file definition shows:
```imageMath.py -e=sqrt(b_0*b_1);abs(a)/(b_0+(b_0==0))/(b_1+(b_1==0))*(b_0!=0)*(b_1!=0) --a=diff_221202-221216_5rlks_28alks.int --b=221202-221216_5rlks_28alks.amp -o 221202-221216_5rlks_28alks.cor -t float -s BIL```

I think the coherence estimation formula is missing a normalization step but any ideas @CunrenLiang ?

**Comment by CunrenLiang** [comment]
Yes, that’s because of floating point number computation, which makes the result sometimes slightly larger than 1.

 

You can make those values smaller than 1, e.g. 0.999, without making another copy of the coherence file by using codes like:

https://github.com/isce-framework/isce2/blob/main/components/isceobj/Alos2Proc/runUnwrapSnaphu.py#L87-L90

 

 

 

From: ***@***.***> on behalf of Emre Havazli ***@***.***>
Reply-To: isce-framework/isce2 ***@***.***>
Date: Thursday, May 23, 2024 at 9:43 AM
To: isce-framework/isce2 ***@***.***>
Cc: Cunren Liang ***@***.***>, Mention ***@***.***>
Subject: [isce-framework/isce2] alosStack estimated interferogram coherence larger than 1 (Issue #847)

 

I am processing ALOS-2 ScanSAR data and I ran into a case where the estimated interferogram coherence exceeds 1:
Band 1 Block=5129x1 Type=Float32, ColorInterp=Undefined
  Minimum=0.000, Maximum=897447.438, Mean=8561.947, StdDev=5409.711
  Metadata:
    STATISTICS_MAXIMUM=897447.4375
    STATISTICS_MEAN=8561.9472832599
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=5409.7114304967
    STATISTICS_VALID_PERCENT=100
Band 2 Block=5129x1 Type=Float32, ColorInterp=Undefined
  Minimum=0.000, Maximum=1.201, Mean=0.487, StdDev=0.237
  Metadata:
    STATISTICS_MAXIMUM=1.2005478143692
    STATISTICS_MEAN=0.48689489981335
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=0.23687659024294
    STATISTICS_VALID_PERCENT=100
The .cor.xml file definition shows:
imageMath.py -e=sqrt(b_0*b_1);abs(a)/(b_0+(b_0==0))/(b_1+(b_1==0))*(b_0!=0)*(b_1!=0) --a=diff_221202-221216_5rlks_28alks.int --b=221202-221216_5rlks_28alks.amp -o 221202-221216_5rlks_28alks.cor -t float -s BIL

I think the coherence estimation formula is missing a normalization step but any ideas @CunrenLiang ?
